services:
  db:
    image: postgres:17-alpine
    container_name: roadvault-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=roadvault
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # Memory optimization for development
      - POSTGRES_SHARED_BUFFERS=64MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=256MB
      - POSTGRES_WORK_MEM=4MB
      - POSTGRES_MAINTENANCE_WORK_MEM=32MB
      - POSTGRES_MAX_CONNECTIONS=50
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      # Optional: Add init scripts if needed
      # - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  maildev:
    image: maildev/maildev:latest
    container_name: roadvault-maildev
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP server
    restart: unless-stopped
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025

volumes:
  postgres_dev_data:
