/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthStatusCheck: typeof import('./src/components/AuthStatusCheck.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    OwnerForm: typeof import('./src/components/OwnerForm.vue')['default']
    PaymentDialog: typeof import('./src/components/PaymentDialog.vue')['default']
    PropertyForm: typeof import('./src/components/PropertyForm.vue')['default']
    PropertyList: typeof import('./src/components/PropertyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
