name: Build and Release Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger on tags matching v*, e.g. v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          LICENSE
          README.md
        body: |
          ## RoadVault Release ${{ github.ref_name }}
          
          Docker image is available at:
          ```
          ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          ```
          
          To use this in your docker-compose.yml:
          ```yaml
          version: '3'
          services:
            roadvault:
              image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
              ports:
                - "8080:8080"
              environment:
                - SPRING_PROFILES_ACTIVE=prod
                # Add any other environment variables here
          ```
